version: 2.1

jobs:
  load:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Execute Python scripts
          command: |
            python ./scripts/gracenote_to_xmltv.py ./channels/gracenote/gracenote.channels.xml -o ./guide/gracenote.xml
            python ./scripts/gracenote_to_xmltv.py ./channels/gracenote/USA-C-BAND-DEFAULT.channels.xml -o ./guide/USA-C-BAND-DEFAULT.xml
            python ./scripts/gracenote_to_xmltv.py ./channels/gracenote/USA-GNSTR-DEFAULT.channels.xml -o ./guide/USA-GNSTR-DEFAULT.xml
            gzip -c ./guide/gracenote.xml > ./guide/gracenote.xml.gz
      
      - run:
          name: Commit and Push Changes
          command: |
            git config --global user.name 'circleci[bot]'
            git config --global user.email 'circleci[bot]@users.noreply.github.com'
            git add --force ./guide
            git commit -m "Update Gracenote XMLTV"
            git push origin main

workflows:
  version: 2
  generate:
    jobs:
      - load:
          filters:
            branches:
              only: main
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only: main
      - push:
          branches:
            only: main
          paths:
            - ".github/workflows/generate.yml"
            - ".circleci/config.yml"
